ktor:
  application:
    name : "atm-monitor-client"
    modules:
      - "com.example.ApplicationKt.module"
  deployment:
    port: 8081

  atm:
    bank: 'axis'
    id: 'axis123'
    baseurl: 'http://localhost:8080/api/v1/atms/'
    token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJhdWQiOiJhdG0tbW9uaXRvci11c2VycyIsInJvbGUiOiJBVE0iLCJ1c2VybmFtZSI6ImF4aXMxMjMiLCJleHAiOjE3NDA3NTAyNTB9.LFIGFe4edUnnFIgYWOFOFzmgGJrOU3W3BI0OunOdxic'

